version: '3'
services:
  app1:
    build: .
    environment:
      - APP_NAME=App1
    ports:
      - "8081:8080"
      # - PORT:8080
    env_file:
      - ./.env  

  app2:
    build: .
    environment:
      - APP_NAME=App2
    ports:
      - "8082:8080"
      # - PORT:8080
    env_file:
      - ./.env  

  app3:
    build: .
    environment:
      - APP_NAME=App3
    ports:
      - "8083:8080"
      # - PORT:8080
    env_file:
      - ./.env  